# Generated by Django 4.2.7 on 2023-11-09 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id_alumno', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45)),
                ('apellidop', models.CharField(blank=True, max_length=45)),
                ('apellidom', models.CharField(blank=True, max_length=45)),
                ('carrera', models.CharField(blank=True, max_length=45)),
                ('num_control', models.IntegerField(blank=True, max_length=15, unique=True)),
                ('sexo', models.CharField(blank=True, max_length=1)),
                ('CURP', models.CharField(blank=True, max_length=45)),
                ('periodo_ingreso', models.DateField()),
                ('periodo_egreso', models.DateField()),
                ('estado_nacimiento', models.CharField(blank=True, max_length=45)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('id_carrera', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_carrera', models.CharField(blank=True, max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Operaciones',
            fields=[
                ('id_operacion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_operacion', models.CharField(blank=True, max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Plan_Estudio',
            fields=[
                ('id_plan', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_plan', models.CharField(blank=True, max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(blank=True, max_length=45)),
                ('operaciones', models.ManyToManyField(to='tasks.operaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=20)),
                ('password', models.CharField(blank=True, max_length=20)),
                ('sal', models.CharField(blank=True, max_length=45)),
                ('date_inicio', models.DateTimeField()),
                ('token', models.CharField(blank=True, max_length=45)),
                ('rol_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Titulados',
            fields=[
                ('id_titulo', models.IntegerField(primary_key=True, serialize=False)),
                ('num_titulo', models.IntegerField(blank=True, max_length=15, unique=True)),
                ('clave_plan', models.CharField(blank=True, max_length=20)),
                ('fecha_acto', models.DateField()),
                ('fecha_registro', models.DateField()),
                ('num_cedula', models.IntegerField(blank=True, max_length=20)),
                ('observaciones', models.TextField(blank=True, max_length=45)),
                ('alumno_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.alumnos')),
            ],
        ),
        migrations.CreateModel(
            name='Certificados',
            fields=[
                ('id_certificado', models.IntegerField(primary_key=True, serialize=False)),
                ('num_folio', models.IntegerField(blank=True, max_length=20)),
                ('nombre_carrera', models.CharField(blank=True, max_length=20)),
                ('fecha_registro', models.DateField()),
                ('observaciones', models.TextField(blank=True, max_length=45)),
                ('alumno_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.alumnos')),
            ],
        ),
        migrations.AddField(
            model_name='alumnos',
            name='carrera_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.carreras'),
        ),
    ]
