# Generated by Django 4.2.7 on 2023-11-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='num_control',
            field=models.IntegerField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='certificados',
            name='num_folio',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='titulados',
            name='num_cedula',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='titulados',
            name='num_titulo',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
