# Generated by Django 4.2.7 on 2023-11-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_alumnos_id_alumno_alter_carreras_id_carrera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='id_alumno',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='carreras',
            name='id_carrera',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='certificados',
            name='id_certificado',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='operaciones',
            name='id_operacion',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plan_estudio',
            name='id_plan',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rol',
            name='id_rol',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='titulados',
            name='id_titulo',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='id_usuario',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
