# Generated by Django 4.2.7 on 2023-11-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_alumnos_id_alumno_alter_carreras_id_carrera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreras',
            name='nombre_carrera',
            field=models.CharField(blank=True, max_length=45, unique=True),
        ),
    ]
