# Generated by Django 4.2.7 on 2023-11-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_carreras_nombre_carrera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificados',
            name='num_folio',
            field=models.IntegerField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='operaciones',
            name='nombre_operacion',
            field=models.CharField(blank=True, max_length=45, unique=True),
        ),
    ]
