# Generated by Django 4.2.7 on 2024-01-10 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_certificados_num_folio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificados',
            name='alumno_fk',
        ),
        migrations.RemoveField(
            model_name='titulados',
            name='alumno_fk',
        ),
        migrations.AddField(
            model_name='alumnos',
            name='certificado_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.certificados'),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='titulo_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.titulados'),
        ),
    ]
