# Generated by Django 4.2.7 on 2024-01-24 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_certificados_alumno_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='carrera_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.carreras'),
        ),
    ]
