# Generated by Django 4.2.7 on 2024-01-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_alumnos_carrera_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='num_control',
            field=models.CharField(blank=True, max_length=45, unique=True),
        ),
    ]
