# Generated by Django 4.2.7 on 2024-02-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_alter_alumnos_carrera_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulados',
            name='num_cedula',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
